; Converted from SDCC assembly to RGBDS
; Original file: menu_strings.s
; Generated by convert_sdcc_to_rgbds.py

	EXPORT _new_game_text_length
	EXPORT _new_game_text
	EXPORT _new_game_text_data
	SECTION "MenuStrings", ROMX
_new_game_text_data:
	db $50
	db $65
	db $6e
	db $69
	db $73
	db $55
	db $54
	db $54
	db $4e
	db $4f
	db $50
	db $54
	db $49
	db $4f
	db $4e
	db $50
_new_game_text:
	db "CUSTOM G"
	db $0a
	db "OPTIONP"
	db $00

; Add the label that the main menu expects
NewGameText::
	db "CUSTOM G"
	db $0a
	db "OPTIONP"
	db $00
_new_game_text_length:
	dw $0010
