#!/usr/bin/env python3
"""
Convert SDCC assembly output to RGBDS-compatible assembly
This allows us to compile C code with GBDK and integrate it with RGBDS builds
"""

import re
import sys
import os

def convert_sdcc_to_rgbds(sdcc_file, output_file):
    """Convert SDCC assembly to RGBDS assembly"""
    
    with open(sdcc_file, 'r') as f:
        lines = f.readlines()
    
    rgbds_lines = []
    rgbds_lines.append("; Converted from SDCC assembly to RGBDS")
    rgbds_lines.append(f"; Original file: {os.path.basename(sdcc_file)}")
    rgbds_lines.append("; Generated by convert_sdcc_to_rgbds.py")
    rgbds_lines.append("")
    
    # Track which sections we've already added
    sections_added = set()
    
    # Process each line
    for line in lines:
        line = line.strip()
        
        # Skip empty lines and SDCC-specific content
        if not line or line.startswith(';---') or line.startswith('.module') or line.startswith('.optsdcc'):
            continue
            
        # Convert SDCC areas to RGBDS sections (avoid duplicates and conflicts)
        if line.startswith('.area _CODE'):
            if 'Code' not in sections_added:
                rgbds_lines.append('\tSECTION "MenuStrings", ROMX')
                sections_added.add('Code')
            continue
        elif line.startswith('.area _DATA'):
            # Skip DATA section to avoid conflicts
            continue
        elif line.startswith('.area _HOME'):
            # Skip HOME section to avoid conflicts with existing home.asm
            continue
        elif line.startswith('.area _'):
            # Skip other SDCC areas
            continue
            
        # Convert global declarations to EXPORT (RGBDS syntax)
        if line.startswith('.globl '):
            symbol = line.split()[1]
            rgbds_lines.append(f'\tEXPORT {symbol}')
            continue
            
        # Convert data directives
        if line.startswith('.db #0x'):
            # Extract hex value and comment (comment is optional)
            match = re.match(r'\.db #0x([0-9a-fA-F]+)(?:\s*;.*)?', line)
            if match:
                hex_val = match.group(1)
                rgbds_lines.append(f'\tdb ${hex_val}')
            continue
        elif line.startswith('.dw #0x'):
            # Extract hex value and comment (comment is optional)
            match = re.match(r'\.dw #0x([0-9a-fA-F]+)(?:\s*;.*)?', line)
            if match:
                hex_val = match.group(1)
                rgbds_lines.append(f'\tdw ${hex_val}')
            continue
        elif line.startswith('.ascii '):
            # Convert ascii directive
            match = re.match(r'\.ascii "([^"]*)"', line)
            if match:
                string_val = match.group(1)
                rgbds_lines.append(f'\tdb "{string_val}"')
            continue
        elif line.startswith('.db 0x'):
            # Convert hex literals to $ format for RGBDS
            match = re.match(r'\.db 0x([0-9a-fA-F]+)', line)
            if match:
                hex_val = match.group(1)
                rgbds_lines.append(f'\tdb ${hex_val}')
            continue
            
        # Skip other SDCC-specific lines
        if any(line.startswith(prefix) for prefix in [
            '; special function registers',
            '; ram data',
            '; absolute external ram data',
            '; global & static initialisations',
            '; Home',
            '; code'
        ]):
            continue
            
        # Keep other lines as-is (labels, etc.)
        if line and not line.startswith(';'):
            rgbds_lines.append(line)
    
    # Add the NewGameText label that the main menu expects
    rgbds_lines.append("")
    rgbds_lines.append("; Add the label that the main menu expects")
    rgbds_lines.append("; NewGameText should point to the actual C data")
    rgbds_lines.append("NewGameText::")
    
    # Parse the actual C-compiled data from SDCC output
    line1_data = []
    line2_data = []
    in_line1_section = False
    in_line2_section = False
    
    for line in lines:
        line = line.strip()
        if line.startswith('_new_game_line1:'):
            in_line1_section = True
            in_line2_section = False
            continue
        elif line.startswith('_new_game_line2:'):
            in_line1_section = False
            in_line2_section = True
            continue
        elif in_line1_section and line.startswith('_'):
            # We've hit the next label, stop copying line1
            in_line1_section = False
        elif in_line2_section and line.startswith('_'):
            # We've hit the next label, stop copying line2
            in_line1_section = False
        elif in_line1_section and line:
            # Copy the line1 data lines
            if line.startswith('.db #0x'):
                match = re.match(r'\.db #0x([0-9a-fA-F]+)', line)
                if match:
                    hex_val = match.group(1)
                    line1_data.append(f'\tdb ${hex_val}')
        elif in_line2_section and line:
            # Copy the line2 data lines
            if line.startswith('.db #0x'):
                match = re.match(r'\.db #0x([0-9a-fA-F]+)', line)
                if match:
                    hex_val = match.group(1)
                    line2_data.append(f'\tdb ${hex_val}')
    
    # Output the first line data using actual C-compiled values
    if line1_data:
        rgbds_lines.append('\t; First line from C compilation:')
        # Convert hex values back to string for the first line
        first_line_chars = []
        for data_line in line1_data:
            # Extract hex value from "db $XX"
            match = re.match(r'\tdb \$([0-9a-fA-F]+)', data_line)
            if match:
                hex_val = int(match.group(1), 16)
                first_line_chars.append(chr(hex_val))
        
        if first_line_chars:
            first_line_str = ''.join(first_line_chars)
            rgbds_lines.append(f'\tdb "{first_line_str}"')
        else:
            rgbds_lines.append('\tdb "NEW GAME"')
    else:
        # Fallback if no data found
        rgbds_lines.append('\t; Fallback data (C compilation may have failed):')
        rgbds_lines.append('\tdb "NEW GAME"')
    
    # Output the second line using the 'next' macro
    if line2_data:
        rgbds_lines.append('\t; Second line from C compilation:')
        # Convert hex values back to string for the next macro
        second_line_chars = []
        for data_line in line2_data:
            # Extract hex value from "db $XX"
            match = re.match(r'\tdb \$([0-9a-fA-F]+)', data_line)
            if match:
                hex_val = int(match.group(1), 16)
                second_line_chars.append(chr(hex_val))
        
        if second_line_chars:
            second_line_str = ''.join(second_line_chars)
            rgbds_lines.append(f'\tnext "{second_line_str}@"')
        else:
            rgbds_lines.append('\tnext "OPTION@"')
    else:
        rgbds_lines.append('\t; Second line (using next macro):')
        rgbds_lines.append('\tnext "OPTION@"')
    
    # Write the converted file
    with open(output_file, 'w') as f:
        f.write('\n'.join(rgbds_lines))
    
    print(f"Converted {sdcc_file} to {output_file}")

def main():
    if len(sys.argv) != 3:
        print("Usage: python3 convert_sdcc_to_rgbds.py <sdcc_file> <output_file>")
        sys.exit(1)
    
    sdcc_file = sys.argv[1]
    output_file = sys.argv[2]
    
    if not os.path.exists(sdcc_file):
        print(f"Error: {sdcc_file} not found")
        sys.exit(1)
    
    convert_sdcc_to_rgbds(sdcc_file, output_file)

if __name__ == "__main__":
    main()
