#!/usr/bin/env python3
"""
Convert SDCC assembly output to RGBDS-compatible assembly
This allows us to compile C code with GBDK and integrate it with RGBDS builds
"""

import re
import sys
import os

def convert_sdcc_to_rgbds(sdcc_file, output_file):
    """Convert SDCC assembly to RGBDS assembly"""
    
    with open(sdcc_file, 'r') as f:
        lines = f.readlines()
    
    rgbds_lines = []
    rgbds_lines.append("; Converted from SDCC assembly to RGBDS")
    rgbds_lines.append(f"; Original file: {os.path.basename(sdcc_file)}")
    rgbds_lines.append("; Generated by convert_sdcc_to_rgbds.py")
    rgbds_lines.append("")
    
    # Track which sections we've already added
    sections_added = set()
    
    # Process each line
    for line in lines:
        line = line.strip()
        
        # Skip empty lines and SDCC-specific content
        if not line or line.startswith(';---') or line.startswith('.module') or line.startswith('.optsdcc'):
            continue
            
        # Convert SDCC areas to RGBDS sections (avoid duplicates and conflicts)
        if line.startswith('.area _CODE'):
            if 'Code' not in sections_added:
                # Use a unique section name based on the input filename
                filename = os.path.basename(sdcc_file).replace('.s', '')
                section_name = filename.replace('_', '').title()
                rgbds_lines.append(f'\tSECTION "{section_name}", ROMX')
                sections_added.add('Code')
            continue
        elif line.startswith('.area _DATA'):
            # Skip DATA section to avoid conflicts
            continue
        elif line.startswith('.area _HOME'):
            # Skip HOME section to avoid conflicts with existing home.asm
            continue
        elif line.startswith('.area _'):
            # Skip other SDCC areas
            continue
            
        # Convert global declarations to EXPORT (RGBDS syntax)
        if line.startswith('.globl '):
            symbol = line.split()[1]
            rgbds_lines.append(f'\tEXPORT {symbol}')
            continue
            
        # Convert data directives
        if line.startswith('.db #0x'):
            # Extract hex value and comment (comment is optional)
            match = re.match(r'\.db #0x([0-9a-fA-F]+)(?:\s*;.*)?', line)
            if match:
                hex_val = match.group(1)
                rgbds_lines.append(f'\tdb ${hex_val}')
            continue
        elif line.startswith('.dw #0x'):
            # Extract hex value and comment (comment is optional)
            match = re.match(r'\.dw #0x([0-9a-fA-F]+)(?:\s*;.*)?', line)
            if match:
                hex_val = match.group(1)
                rgbds_lines.append(f'\tdw ${hex_val}')
            continue
        elif line.startswith('.ascii '):
            # Convert ascii directive
            match = re.match(r'\.ascii "([^"]*)"', line)
            if match:
                string_val = match.group(1)
                rgbds_lines.append(f'\tdb "{string_val}"')
            continue
        elif line.startswith('.db 0x'):
            # Convert hex literals to $ format for RGBDS
            match = re.match(r'\.db 0x([0-9a-fA-F]+)', line)
            if match:
                hex_val = match.group(1)
                rgbds_lines.append(f'\tdb ${hex_val}')
            continue
            
        # Convert SDCC-specific syntax to RGBDS syntax
        # Convert #_symbol to symbol (remove # and _)
        if '#' in line:
            line = re.sub(r'#_([a-zA-Z_][a-zA-Z0-9_]*)', r'\1', line)
            
        # Fix remaining _symbol patterns (remove extra underscores)
        if '_' in line:
            line = re.sub(r'\[_([a-zA-Z_][a-zA-Z0-9_]*)\s*\+\s*([0-9]+)\]', r'[\1 + \2]', line)
            line = re.sub(r'\[_([a-zA-Z_][a-zA-Z0-9_]*)\]', r'[\1]', line)
            
        # Final cleanup: remove any remaining underscores in bracket expressions
        if '[' in line and '_' in line:
            line = re.sub(r'\[_([a-zA-Z_][a-zA-Z0-9_]*)\]', r'[\1]', line)
            
        # Direct replacement for common patterns
        if '_wPlayerMoney' in line:
            line = line.replace('[_wPlayerMoney', '[wPlayerMoney')
            line = line.replace('_wPlayerMoney', 'wPlayerMoney')
            
        # Fix missing spaces around + operator
        if '+' in line:
            line = re.sub(r'([a-zA-Z_][a-zA-Z0-9_]*)\+([0-9]+)', r'\1 + \2', line)
            
        # Convert #(symbol) to [symbol] (change parentheses to brackets)
        if '#' in line and '(' in line and ')' in line:
            line = re.sub(r'#\(([^)]+)\)', r'[\1]', line)
            
        # Fix RGBDS addressing: ld hl, [wPlayerMoney + 1] should be ld hl, wPlayerMoney + 1
        if 'ld' in line and 'hl,' in line and '[' in line and ']' in line:
            line = re.sub(r'ld\s+hl,\s*\[([^\]]+)\]', r'ld\t\thl, \1', line)
            
        # Fix malformed ld instructions with extra tabs
        if line.startswith('ld\t\t'):
            line = line.replace('ld\t\t', 'ld\t')
            
        # Fix malformed ld instructions with missing operands
        if 'ld\t\t' in line:
            line = line.replace('ld\t\t', 'ld\t')
            
        # Fix specific malformed ld instructions
        if line.startswith('ld\t\t'):
            line = line.replace('ld\t\t', 'ld\t')
            
        # Fix lines with multiple tabs
        if '\t\t' in line:
            line = line.replace('\t\t', '\t')
            
        # Convert #0x to $ (hex values)
        if '#' in line and '0x' in line:
            line = re.sub(r'#0x([0-9a-fA-F]+)', r'$\1', line)
            
        # Convert (hl) to [hl] (indirect addressing)
        if '(hl)' in line:
            line = line.replace('(hl)', '[hl]')
        if '(bc)' in line:
            line = line.replace('(bc)', '[bc]')
        if '(de)' in line:
            line = line.replace('(de)', '[de]')
            
        # Skip other SDCC-specific lines
        if any(line.startswith(prefix) for prefix in [
            '; special function registers',
            '; ram data',
            '; absolute external ram data',
            '; global & static initialisations',
            '; Home',
            '; code'
        ]):
            continue
            
        # Handle C source comments (convert them to regular assembly comments)
        if line.startswith(';c_code/'):
            # Convert C source comments to regular assembly comments
            comment = line.replace(';c_code/', '; C: ')
            rgbds_lines.append(comment)
            continue
            
        # Keep other lines as-is (labels, etc.)
        if line and not line.startswith(';'):
            rgbds_lines.append(line)
    

    

    
    # Write the converted file
    with open(output_file, 'w') as f:
        f.write('\n'.join(rgbds_lines))
    
    print(f"Converted {sdcc_file} to {output_file}")

def main():
    if len(sys.argv) != 3:
        print("Usage: python3 convert_sdcc_to_rgbds.py <sdcc_file> <output_file>")
        sys.exit(1)
    
    sdcc_file = sys.argv[1]
    output_file = sys.argv[2]
    
    if not os.path.exists(sdcc_file):
        print(f"Error: {sdcc_file} not found")
        sys.exit(1)
    
    convert_sdcc_to_rgbds(sdcc_file, output_file)

if __name__ == "__main__":
    main()
