; Converted from SDCC assembly to RGBDS
; Original file: game_operations.s
; Generated by convert_sdcc_to_rgbds.py

	EXPORT _give_master_kit
	EXPORT _give_battle_kit
	EXPORT _give_starter_kit
	EXPORT _give_max_revives
	EXPORT _give_revives
	EXPORT _give_full_restores
	EXPORT _give_hyper_potions
	EXPORT _give_super_potions
	EXPORT _give_potions
	EXPORT _give_ultra_balls
	EXPORT _give_great_balls
	EXPORT _give_lots_of_pokeballs
	EXPORT _give_pokeballs
	EXPORT _clear_bag
	EXPORT _give_twenty_five_thousand
	EXPORT _give_fifteen_thousand
	EXPORT _give_nine_thousand
	EXPORT _give_five_thousand
	EXPORT _give_one_thousand
	EXPORT _give_hundred_thousand
	EXPORT _give_fifty_thousand
	EXPORT _give_ten_thousand
	SECTION "Gameoperations", ROMX
; C: game_operations.c:19: void give_ten_thousand(void) {
_give_ten_thousand::
; C: game_operations.c:20: wPlayerMoney[0] = 0x01;  // 1 × 10,000 = $10,000
ld	hl, wPlayerMoney
ld	[hl], $01
; C: game_operations.c:21: wPlayerMoney[1] = 0x00;  // 0 × 100 = $0
ld	hl, wPlayerMoney + 1
ld	[hl], $00
; C: game_operations.c:22: wPlayerMoney[2] = 0x00;  // 0 × 1 = $0
ld	hl, wPlayerMoney + 2
ld	[hl], $00
; C: game_operations.c:23: }
ret
; C: game_operations.c:26: void give_fifty_thousand(void) {
_give_fifty_thousand::
; C: game_operations.c:27: wPlayerMoney[0] = 0x05;  // 5 × 10,000 = $50,000
ld	hl, wPlayerMoney
ld	[hl], $05
; C: game_operations.c:28: wPlayerMoney[1] = 0x00;  // 0 × 100 = $0
ld	hl, wPlayerMoney + 1
ld	[hl], $00
; C: game_operations.c:29: wPlayerMoney[2] = 0x00;  // 0 × 1 = $0
ld	hl, wPlayerMoney + 2
ld	[hl], $00
; C: game_operations.c:30: }
ret
; C: game_operations.c:33: void give_hundred_thousand(void) {
_give_hundred_thousand::
; C: game_operations.c:34: wPlayerMoney[0] = 0x0A;  // 10 × 10,000 = $100,000
ld	hl, wPlayerMoney
ld	[hl], $0a
; C: game_operations.c:35: wPlayerMoney[1] = 0x00;  // 0 × 100 = $0
ld	hl, wPlayerMoney + 1
ld	[hl], $00
; C: game_operations.c:36: wPlayerMoney[2] = 0x00;  // 0 × 1 = $0
ld	hl, wPlayerMoney + 2
ld	[hl], $00
; C: game_operations.c:37: }
ret
; C: game_operations.c:40: void give_one_thousand(void) {
_give_one_thousand::
; C: game_operations.c:41: wPlayerMoney[0] = 0x00;  // 0 × 10,000 = $0
ld	bc, wPlayerMoney + 0
xor	a, a
ld	[bc], a
; C: game_operations.c:42: wPlayerMoney[1] = 0x0A;  // 10 × 100 = $1,000
ld	hl, wPlayerMoney + 1
ld	[hl], $0a
; C: game_operations.c:43: wPlayerMoney[2] = 0x00;  // 0 × 1 = $0
inc	bc
inc	bc
xor	a, a
ld	[bc], a
; C: game_operations.c:44: }
ret
; C: game_operations.c:47: void give_five_thousand(void) {
_give_five_thousand::
; C: game_operations.c:48: wPlayerMoney[0] = 0x00;  // 0 × 10,000 = $0
ld	bc, wPlayerMoney + 0
xor	a, a
ld	[bc], a
; C: game_operations.c:49: wPlayerMoney[1] = 0x32;  // 50 × 100 = $5,000
ld	hl, wPlayerMoney + 1
ld	[hl], $32
; C: game_operations.c:50: wPlayerMoney[2] = 0x00;  // 0 × 1 = $0
inc	bc
inc	bc
xor	a, a
ld	[bc], a
; C: game_operations.c:51: }
ret
; C: game_operations.c:54: void give_nine_thousand(void) {
_give_nine_thousand::
; C: game_operations.c:55: wPlayerMoney[0] = 0x00;  // 0 × 10,000 = $0
ld	bc, wPlayerMoney + 0
xor	a, a
ld	[bc], a
; C: game_operations.c:56: wPlayerMoney[1] = 0x5A;  // 90 × 100 = $9,000
ld	hl, wPlayerMoney + 1
ld	[hl], $5a
; C: game_operations.c:57: wPlayerMoney[2] = 0x00;  // 0 × 1 = $0
inc	bc
inc	bc
xor	a, a
ld	[bc], a
; C: game_operations.c:58: }
ret
; C: game_operations.c:61: void give_fifteen_thousand(void) {
_give_fifteen_thousand::
; C: game_operations.c:62: wPlayerMoney[0] = 0x01;  // 1 × 10,000 = $10,000
ld	hl, wPlayerMoney
ld	[hl], $01
; C: game_operations.c:63: wPlayerMoney[1] = 0x32;  // 50 × 100 = $5,000
ld	hl, wPlayerMoney + 1
ld	[hl], $32
; C: game_operations.c:64: wPlayerMoney[2] = 0x00;  // 0 × 1 = $0
ld	hl, wPlayerMoney + 2
ld	[hl], $00
; C: game_operations.c:65: }
ret
; C: game_operations.c:68: void give_twenty_five_thousand(void) {
_give_twenty_five_thousand::
; C: game_operations.c:69: wPlayerMoney[0] = 0x02;  // 2 × 10,000 = $20,000
ld	hl, wPlayerMoney
ld	[hl], $02
; C: game_operations.c:70: wPlayerMoney[1] = 0x32;  // 50 × 100 = $5,000
ld	hl, wPlayerMoney + 1
ld	[hl], $32
; C: game_operations.c:71: wPlayerMoney[2] = 0x00;  // 0 × 1 = $0
ld	hl, wPlayerMoney + 2
ld	[hl], $00
; C: game_operations.c:72: }
ret
; C: game_operations.c:79: void clear_bag(void) {
_clear_bag::
; C: game_operations.c:80: wNumBagItems = 0;
ld	hl, wNumBagItems
ld	[hl], $00
; C: game_operations.c:81: }
ret
; C: game_operations.c:84: void give_pokeballs(void) {
_give_pokeballs::
; C: game_operations.c:88: }
ret
; C: game_operations.c:91: void give_lots_of_pokeballs(void) {
_give_lots_of_pokeballs::
; C: game_operations.c:92: if (wNumBagItems < 59) {
ld	hl, wNumBagItems
ld	a, [hl]
sub	a, $3b
ret	NC
; C: game_operations.c:93: wBagItems[wNumBagItems * 2] = 0x04;      // POKE_BALL item ID
ld	bc, wBagItems + 0
ld	l, [hl]
ld	h, $00
add	hl, hl
add	hl, bc
ld	[hl], $04
; C: game_operations.c:94: wBagItems[wNumBagItems * 2 + 1] = 10;    // Quantity: 10
ld	hl, wNumBagItems
ld	l, [hl]
ld	h, $00
add	hl, hl
inc	hl
add	hl, bc
ld	[hl], $0a
; C: game_operations.c:95: wNumBagItems++;
ld	hl, wNumBagItems
inc	[hl]
; C: game_operations.c:97: }
ret
; C: game_operations.c:100: void give_great_balls(void) {
_give_great_balls::
; C: game_operations.c:101: if (wNumBagItems < 59) {
ld	hl, wNumBagItems
ld	a, [hl]
sub	a, $3b
ret	NC
; C: game_operations.c:102: wBagItems[wNumBagItems * 2] = 0x03;      // GREAT_BALL item ID
ld	bc, wBagItems + 0
ld	l, [hl]
ld	h, $00
add	hl, hl
add	hl, bc
ld	[hl], $03
; C: game_operations.c:103: wBagItems[wNumBagItems * 2 + 1] = 5;     // Quantity: 5
ld	hl, wNumBagItems
ld	l, [hl]
ld	h, $00
add	hl, hl
inc	hl
add	hl, bc
ld	[hl], $05
; C: game_operations.c:104: wNumBagItems++;
ld	hl, wNumBagItems
inc	[hl]
; C: game_operations.c:106: }
ret
; C: game_operations.c:109: void give_ultra_balls(void) {
_give_ultra_balls::
; C: game_operations.c:110: if (wNumBagItems < 59) {
ld	hl, wNumBagItems
ld	a, [hl]
sub	a, $3b
ret	NC
; C: game_operations.c:111: wBagItems[wNumBagItems * 2] = 0x02;      // ULTRA_BALL item ID
ld	bc, wBagItems + 0
ld	l, [hl]
ld	h, $00
add	hl, hl
add	hl, bc
ld	[hl], $02
; C: game_operations.c:112: wBagItems[wNumBagItems * 2 + 1] = 5;     // Quantity: 5
ld	hl, wNumBagItems
ld	l, [hl]
ld	h, $00
add	hl, hl
inc	hl
add	hl, bc
ld	[hl], $05
; C: game_operations.c:113: wNumBagItems++;
ld	hl, wNumBagItems
inc	[hl]
; C: game_operations.c:115: }
ret
; C: game_operations.c:118: void give_potions(void) {
_give_potions::
; C: game_operations.c:119: if (wNumBagItems < 59) {
ld	hl, wNumBagItems
ld	a, [hl]
sub	a, $3b
ret	NC
; C: game_operations.c:120: wBagItems[wNumBagItems * 2] = 0x14;      // POTION item ID
ld	bc, wBagItems + 0
ld	l, [hl]
ld	h, $00
add	hl, hl
add	hl, bc
ld	[hl], $14
; C: game_operations.c:121: wBagItems[wNumBagItems * 2 + 1] = 5;     // Quantity: 5
ld	hl, wNumBagItems
ld	l, [hl]
ld	h, $00
add	hl, hl
inc	hl
add	hl, bc
ld	[hl], $05
; C: game_operations.c:122: wNumBagItems++;
ld	hl, wNumBagItems
inc	[hl]
; C: game_operations.c:124: }
ret
; C: game_operations.c:127: void give_super_potions(void) {
_give_super_potions::
; C: game_operations.c:128: if (wNumBagItems < 59) {
ld	hl, wNumBagItems
ld	a, [hl]
sub	a, $3b
ret	NC
; C: game_operations.c:129: wBagItems[wNumBagItems * 2] = 0x13;      // SUPER_POTION item ID
ld	bc, wBagItems + 0
ld	l, [hl]
ld	h, $00
add	hl, hl
add	hl, bc
ld	[hl], $13
; C: game_operations.c:130: wBagItems[wNumBagItems * 2 + 1] = 5;     // Quantity: 5
ld	hl, wNumBagItems
ld	l, [hl]
ld	h, $00
add	hl, hl
inc	hl
add	hl, bc
ld	[hl], $05
; C: game_operations.c:131: wNumBagItems++;
ld	hl, wNumBagItems
inc	[hl]
; C: game_operations.c:133: }
ret
; C: game_operations.c:136: void give_hyper_potions(void) {
_give_hyper_potions::
; C: game_operations.c:137: if (wNumBagItems < 59) {
ld	hl, wNumBagItems
ld	a, [hl]
sub	a, $3b
ret	NC
; C: game_operations.c:138: wBagItems[wNumBagItems * 2] = 0x12;      // HYPER_POTION item ID
ld	bc, wBagItems + 0
ld	l, [hl]
ld	h, $00
add	hl, hl
add	hl, bc
ld	[hl], $12
; C: game_operations.c:139: wBagItems[wNumBagItems * 2 + 1] = 5;     // Quantity: 5
ld	hl, wNumBagItems
ld	l, [hl]
ld	h, $00
add	hl, hl
inc	hl
add	hl, bc
ld	[hl], $05
; C: game_operations.c:140: wNumBagItems++;
ld	hl, wNumBagItems
inc	[hl]
; C: game_operations.c:142: }
ret
; C: game_operations.c:145: void give_full_restores(void) {
_give_full_restores::
; C: game_operations.c:146: if (wNumBagItems < 59) {
ld	hl, wNumBagItems
ld	a, [hl]
sub	a, $3b
ret	NC
; C: game_operations.c:147: wBagItems[wNumBagItems * 2] = 0x10;      // FULL_RESTORE item ID
ld	bc, wBagItems + 0
ld	l, [hl]
ld	h, $00
add	hl, hl
add	hl, bc
ld	[hl], $10
; C: game_operations.c:148: wBagItems[wNumBagItems * 2 + 1] = 5;     // Quantity: 5
ld	hl, wNumBagItems
ld	l, [hl]
ld	h, $00
add	hl, hl
inc	hl
add	hl, bc
ld	[hl], $05
; C: game_operations.c:149: wNumBagItems++;
ld	hl, wNumBagItems
inc	[hl]
; C: game_operations.c:151: }
ret
; C: game_operations.c:154: void give_revives(void) {
_give_revives::
; C: game_operations.c:155: if (wNumBagItems < 59) {
ld	hl, wNumBagItems
ld	a, [hl]
sub	a, $3b
ret	NC
; C: game_operations.c:156: wBagItems[wNumBagItems * 2] = 0x35;      // REVIVE item ID
ld	bc, wBagItems + 0
ld	l, [hl]
ld	h, $00
add	hl, hl
add	hl, bc
ld	[hl], $35
; C: game_operations.c:157: wBagItems[wNumBagItems * 2 + 1] = 5;     // Quantity: 5
ld	hl, wNumBagItems
ld	l, [hl]
ld	h, $00
add	hl, hl
inc	hl
add	hl, bc
ld	[hl], $05
; C: game_operations.c:158: wNumBagItems++;
ld	hl, wNumBagItems
inc	[hl]
; C: game_operations.c:160: }
ret
; C: game_operations.c:163: void give_max_revives(void) {
_give_max_revives::
; C: game_operations.c:164: if (wNumBagItems < 59) {
ld	hl, wNumBagItems
ld	a, [hl]
sub	a, $3b
ret	NC
; C: game_operations.c:165: wBagItems[wNumBagItems * 2] = 0x36;      // MAX_REVIVE item ID
ld	bc, wBagItems + 0
ld	l, [hl]
ld	h, $00
add	hl, hl
add	hl, bc
ld	[hl], $36
; C: game_operations.c:166: wBagItems[wNumBagItems * 2 + 1] = 5;     // Quantity: 5
ld	hl, wNumBagItems
ld	l, [hl]
ld	h, $00
add	hl, hl
inc	hl
add	hl, bc
ld	[hl], $05
; C: game_operations.c:167: wNumBagItems++;
ld	hl, wNumBagItems
inc	[hl]
; C: game_operations.c:169: }
ret
; C: game_operations.c:172: void give_starter_kit(void) {
_give_starter_kit::
; C: game_operations.c:173: give_pokeballs();
call	_give_pokeballs
; C: game_operations.c:174: give_potions();
; C: game_operations.c:175: }
jp	_give_potions
; C: game_operations.c:178: void give_battle_kit(void) {
_give_battle_kit::
; C: game_operations.c:179: give_great_balls();
call	_give_great_balls
; C: game_operations.c:180: give_super_potions();
call	_give_super_potions
; C: game_operations.c:181: give_revives();
; C: game_operations.c:182: }
jp	_give_revives
; C: game_operations.c:185: void give_master_kit(void) {
_give_master_kit::
; C: game_operations.c:186: give_ultra_balls();
call	_give_ultra_balls
; C: game_operations.c:187: give_hyper_potions();
call	_give_hyper_potions
; C: game_operations.c:188: give_max_revives();
; C: game_operations.c:189: }
jp	_give_max_revives