#!/usr/bin/env python3
"""
String Generator for Pokemon Yellow Legacy
This script reads a C-like configuration and generates assembly files
"""

import re
import sys
import os

def parse_c_strings(c_file_path):
    """Parse C file and extract string definitions"""
    strings = {}
    
    try:
        with open(c_file_path, 'r') as f:
            content = f.read()
            
        # Find the specific array we want by looking for the start and end
        start_pattern = r'const\s+uint8_t\s+new_game_text_data\[\]\s*=\s*\{'
        start_match = re.search(start_pattern, content)
        
        if start_match:
            start_pos = start_match.end()
            
            # Find the matching closing brace by counting braces
            brace_count = 1
            pos = start_pos
            
            while pos < len(content) and brace_count > 0:
                if content[pos] == '{':
                    brace_count += 1
                elif content[pos] == '}':
                    brace_count -= 1
                pos += 1
                
            if brace_count == 0:
                end_pos = pos - 1
                array_content = content[start_pos:end_pos]
                
                # Parse the array content
                string_data = []
                lines = array_content.split('\n')
                
                for i, line in enumerate(lines):
                    line = line.strip()
                    
                    # Remove comments
                    if '//' in line:
                        line = line.split('//')[0].strip()
                    if '/*' in line:
                        line = line.split('/*')[0].strip()
                        
                    # Skip empty lines
                    if not line:
                        continue
                        
                    # Remove trailing comma
                    if line.endswith(','):
                        line = line[:-1].strip()
                        
                    # Split by comma to handle multiple values per line
                    parts = [p.strip() for p in line.split(',')]
                    
                    for part in parts:
                        if not part:
                            continue
                            
                        if part.startswith("'") and part.endswith("'"):
                            # Single character
                            char = part[1:-1]
                            if char == '\\n':
                                string_data.append(0x4E)  # <NEXT> character
                            elif char == '\\x50':
                                string_data.append(0x50)  # "@" terminator
                            else:
                                string_data.append(ord(char))
                        elif part.startswith('0x'):
                            # Hex value
                            string_data.append(int(part, 16))
                        elif part.isdigit():
                            # Decimal value
                            string_data.append(int(part))
                            
                if string_data:
                    strings['new_game_text_data'] = string_data
                    
    except FileNotFoundError:
        print(f"Warning: {c_file_path} not found")
    except Exception as e:
        print(f"Error parsing {c_file_path}: {e}")
        
    return strings

def generate_assembly(strings, output_path):
    """Generate assembly file from parsed strings"""
    
    assembly_content = f"""; Auto-generated assembly file from C-like definitions
; Generated by generate_strings.py
; Do not edit this file directly - edit the C file instead

SECTION "Menu Strings", ROMX

"""
    
    for name, data in strings.items():
        assembly_content += f"{name}:\n"
        
        # Convert to assembly db statements
        line_data = []
        for byte in data:
            if 32 <= byte <= 126:  # Printable ASCII
                line_data.append(f'"{chr(byte)}"')
            else:
                line_data.append(f"${byte:02X}")
                
        # Split into lines of reasonable length
        for i in range(0, len(line_data), 8):
            chunk = line_data[i:i+8]
            assembly_content += f"\tdb {', '.join(chunk)}\n"
            
        assembly_content += "\n"
    
    # Add the NewGameText label that the main menu expects
    if 'new_game_text_data' in strings:
        assembly_content += """NewGameText::
"""
        # Parse the string data to find where to insert 'next' directives
        data = strings['new_game_text_data']
        
        # Find the newline character (0x4E) to split the text
        newline_pos = -1
        for i, byte in enumerate(data):
            if byte == 0x4E:  # <NEXT> character
                newline_pos = i
                break
        
        if newline_pos != -1:
            # First line: characters before newline
            first_line = data[:newline_pos]
            # Second line: characters after newline (excluding the newline itself and terminator)
            second_line = data[newline_pos + 1:-1]  # Exclude the last byte (0x50 terminator)
            
            # Generate first line
            if first_line:
                line_data = []
                for byte in first_line:
                    if 32 <= byte <= 126:  # Printable ASCII
                        line_data.append(f'"{chr(byte)}"')
                    else:
                        line_data.append(f"${byte:02X}")
                
                # Split into reasonable chunks
                for i in range(0, len(line_data), 8):
                    chunk = line_data[i:i+8]
                    assembly_content += f"\tdb {', '.join(chunk)}\n"
            
            # Add next directive
            assembly_content += "\tnext\n"
            
            # Generate second line
            if second_line:
                line_data = []
                for byte in second_line:
                    if 32 <= byte <= 126:  # Printable ASCII
                        line_data.append(f'"{chr(byte)}"')
                    else:
                        line_data.append(f"${byte:02X}")
                
                # Split into reasonable chunks
                for i in range(0, len(line_data), 8):
                    chunk = line_data[i:i+8]
                    assembly_content += f"\tdb {', '.join(chunk)}\n"
        else:
            # Fallback: no newline found, generate as single line (excluding terminator)
            line_data = []
            for byte in data[:-1]:  # Exclude the last byte (0x50 terminator)
                if 32 <= byte <= 126:  # Printable ASCII
                    line_data.append(f'"{chr(byte)}"')
                else:
                    line_data.append(f"${byte:02X}")
                    
            # Split into lines of reasonable length
            for i in range(0, len(line_data), 8):
                chunk = line_data[i:i+8]
                assembly_content += f"\tdb {', '.join(chunk)}\n"
    
    try:
        with open(output_path, 'w') as f:
            f.write(assembly_content)
        print(f"Generated {output_path}")
    except Exception as e:
        print(f"Error writing {output_path}: {e}")

def main():
    c_file = "c_code/menu_strings.c"
    asm_file = "c_code/menu_strings.asm"
    
    print("Parsing C file...")
    strings = parse_c_strings(c_file)
    
    if not strings:
        print("No strings found in C file")
        return
        
    print(f"Found {len(strings)} string definitions:")
    for name, data in strings.items():
        print(f"  {name}: {len(data)} bytes")
        
    print("\nGenerating assembly file...")
    generate_assembly(strings, asm_file)
    
    print("Done! Now you can:")
    print("1. Edit strings in menu_strings.c")
    print("2. Run: python3 c_code/generate_strings.py")
    print("3. Build the ROM with: make")

if __name__ == "__main__":
    main()
