; Auto-generated assembly file from C-like definitions
; Generated by generate_strings.py
; Do not edit this file directly - edit the C file instead

SECTION "Menu Strings", ROMX

new_game_text_data:
	db "P", "e", "n", "i", "s", "U", "T", "T"
	db "N", "O", "P", "T", "I", "O", "N", "P"

NewGameText::
	db "P", "e", "n", "i", "s", "U", "T", "T"
	next
	db "O", "P", "T", "I", "O", "N"
