; Converted from SDCC assembly to RGBDS
; Original file: menu_strings.s
; Generated by convert_sdcc_to_rgbds.py

	EXPORT _new_game_line2_length
	EXPORT _new_game_line1_length
	EXPORT _new_game_line2_str
	EXPORT _new_game_line1_str
	EXPORT _new_game_line2
	EXPORT _new_game_line1
	SECTION "MenuStrings", ROMX
_new_game_line1:
	db $50
	db $45
	db $4e
	db $49
	db $53
	db $20
	db $47
_new_game_line2:
	db $4f
	db $50
	db $54
	db $49
	db $4f
	db $4e
_new_game_line1_str:
	db "PENIS G"
	db $00
_new_game_line2_str:
	db "OPTION"
	db $00
_new_game_line1_length:
	dw $0007
_new_game_line2_length:
	dw $0006

; Add the label that the main menu expects
; NewGameText should point to the actual C data
NewGameText::
	; First line from C compilation:
	db "PENIS G"
	; Second line from C compilation:
	next "OPTION@"