; Converted from SDCC assembly to RGBDS
; Original file: money_management.s
; Generated by convert_sdcc_to_rgbds.py

	EXPORT _give_ten_thousand_final
	EXPORT _give_ten_thousand_bcd
	EXPORT _give_little_money
	EXPORT _give_some_money
	EXPORT _give_lots_of_money
	EXPORT _give_max_money
	EXPORT _give_starting_money
	EXPORT _test_normal_money
	SECTION "Moneymanagement", ROMX
; C: money_management.c:11: void test_normal_money(void) {
_test_normal_money::
; C: money_management.c:12: wPlayerMoney[0] = 0x00;  // Low byte
ld	bc, wPlayerMoney + 0
xor	a, a
ld	[bc], a
; C: money_management.c:13: wPlayerMoney[1] = 0x30;  // Middle byte (what game normally sets)
ld		hl, wPlayerMoney + 1
ld	[hl], $30
; C: money_management.c:14: wPlayerMoney[2] = 0x00;  // High byte
inc	bc
inc	bc
xor	a, a
ld	[bc], a
; C: money_management.c:15: }
ret
; C: money_management.c:18: void give_starting_money(void) {
_give_starting_money::
; C: money_management.c:19: wPlayerMoney[0] = 0x00;  // Low byte
ld	bc, wPlayerMoney + 0
xor	a, a
ld	[bc], a
; C: money_management.c:20: wPlayerMoney[1] = 0x30;  // Middle byte ($3000)
ld		hl, wPlayerMoney + 1
ld	[hl], $30
; C: money_management.c:21: wPlayerMoney[2] = 0x00;  // High byte
inc	bc
inc	bc
xor	a, a
ld	[bc], a
; C: money_management.c:22: }
ret
; C: money_management.c:25: void give_max_money(void) {
_give_max_money::
; C: money_management.c:26: wPlayerMoney[0] = 0x99;  // Low byte (99)
ld	hl, wPlayerMoney
ld	[hl], $99
; C: money_management.c:27: wPlayerMoney[1] = 0x99;  // Middle byte (99)
ld		hl, wPlayerMoney + 1
ld	[hl], $99
; C: money_management.c:28: wPlayerMoney[2] = 0x99;  // High byte (99)
ld		hl, wPlayerMoney + 2
ld	[hl], $99
; C: money_management.c:29: }
ret
; C: money_management.c:32: void give_lots_of_money(void) {
_give_lots_of_money::
; C: money_management.c:33: wPlayerMoney[0] = 0x00;  // Low byte (00)
ld	hl, wPlayerMoney
ld	[hl], $00
; C: money_management.c:34: wPlayerMoney[1] = 0x00;  // Middle byte (00)
ld		hl, wPlayerMoney + 1
ld	[hl], $00
; C: money_management.c:35: wPlayerMoney[2] = 0x10;  // High byte (10 = 100,000)
ld		hl, wPlayerMoney + 2
ld	[hl], $10
; C: money_management.c:36: }
ret
; C: money_management.c:39: void give_some_money(void) {
_give_some_money::
; C: money_management.c:40: wPlayerMoney[0] = 0x00;  // Low byte
ld	bc, wPlayerMoney + 0
xor	a, a
ld	[bc], a
; C: money_management.c:41: wPlayerMoney[1] = 0x10;  // Middle byte (trying $10 = 16 in decimal)
ld		hl, wPlayerMoney + 1
ld	[hl], $10
; C: money_management.c:42: wPlayerMoney[2] = 0x00;  // High byte
inc	bc
inc	bc
xor	a, a
ld	[bc], a
; C: money_management.c:43: }
ret
; C: money_management.c:46: void give_little_money(void) {
_give_little_money::
; C: money_management.c:47: wPlayerMoney[0] = 0x00;  // Low byte (00)
ld	bc, wPlayerMoney + 0
xor	a, a
ld	[bc], a
; C: money_management.c:48: wPlayerMoney[1] = 0x10;  // Middle byte (10 = 1,000)
ld		hl, wPlayerMoney + 1
ld	[hl], $10
; C: money_management.c:49: wPlayerMoney[2] = 0x00;  // High byte (00)
inc	bc
inc	bc
xor	a, a
ld	[bc], a
; C: money_management.c:50: }
ret
; C: money_management.c:53: void give_ten_thousand_bcd(void) {
_give_ten_thousand_bcd::
; C: money_management.c:54: wPlayerMoney[0] = 0x10;  // Low byte (0x10 = 16 in decimal, 16 × 1000 = $16,000)
ld	hl, wPlayerMoney
ld	[hl], $10
; C: money_management.c:55: wPlayerMoney[1] = 0x00;  // Middle byte (0x00 = 0 in decimal, 0 × 100 = $0)
ld		hl, wPlayerMoney + 1
ld	[hl], $00
; C: money_management.c:56: wPlayerMoney[2] = 0x00;  // High byte (0x00 = 0 in decimal, 0 × 1 = $0)
ld		hl, wPlayerMoney + 2
ld	[hl], $00
; C: money_management.c:57: }
ret
; C: money_management.c:60: void give_ten_thousand_final(void) {
_give_ten_thousand_final::
; C: money_management.c:61: wPlayerMoney[0] = 0x01;  // Low byte (0x01 = 1 in decimal, 1 × 10,000 = $10,000)
ld	hl, wPlayerMoney
ld	[hl], $01
; C: money_management.c:62: wPlayerMoney[1] = 0x00;  // Middle byte (0x00 = 0 in decimal, 0 × 100 = $0)
ld		hl, wPlayerMoney + 1
ld	[hl], $00
; C: money_management.c:63: wPlayerMoney[2] = 0x00;  // High byte (0x00 = 0 in decimal, 0 × 1 = $0)
ld		hl, wPlayerMoney + 2
ld	[hl], $00
; C: money_management.c:64: }
ret