; Converted from SDCC assembly to RGBDS
; Original file: menu_strings.s
; Generated by convert_sdcc_to_rgbds.py

	EXPORT _new_game_text_length
	EXPORT _new_game_text
	EXPORT _new_game_text_data
	SECTION "MenuStrings", ROMX
_new_game_text_data:
	db $50
	db $65
	db $6e
	db $69
	db $73
	db $20
	db $47
	db $3c
	db $4e
	db $45
	db $58
	db $54
	db $3e
	db $4f
	db $50
	db $54
	db $49
	db $4f
	db $4e
	db $40
_new_game_text:
	db "Penis G<NEXT>OPTION@"
	db $00
_new_game_text_length:
	dw $0014

; Add the label that the main menu expects
; NewGameText should point to the actual C data
NewGameText::
	; First line: "Penis G"
	db "Penis G"
	; Second line: "OPTION@" (using next macro)
	next "OPTION@"